# Generated by Django 4.0.6 on 2024-04-04 06:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expire_date',
            field=models.DateField(default=users.models.get_today),
        ),
    ]
