# Generated by Django 4.0.6 on 2024-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
