# Generated by Django 4.0.6 on 2024-04-12 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_advisorrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
