# Generated by Django 4.0.6 on 2024-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_grade_max_question_grade_max_test_grade_max_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='test_score',
            field=models.FloatField(default=0),
        ),
    ]
