# Generated by Django 5.0.4 on 2024-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_advisor_comment_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
