# Generated by Django 4.0.6 on 2024-03-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_banner_tutorialvideo_university_remove_student_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('time', models.TimeField()),
                ('question', models.IntegerField(default=0)),
                ('test', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
