# Generated by Django 4.0.6 on 2024-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueitem',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
