# Generated by Django 4.0.6 on 2024-04-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_field'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
