# Generated by Django 5.0.4 on 2024-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='type',
            field=models.CharField(choices=[('app', 'App'), ('advisor', 'Advisor')], default='app', max_length=30),
        ),
    ]
