# Generated by Django 4.0.6 on 2024-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarinpalMerchantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
            ],
        ),
    ]
