# Generated by Django 4.2.7 on 2023-12-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_student_invitation_code_wallet'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('test', 'Test'), ('tashrihi', 'Tashrihi')], default='test', max_length=255)),
                ('question_count', models.IntegerField(default=0)),
                ('test_type', models.CharField(choices=[('test', 'Test'), ('exam', 'Exam')], default='test', max_length=255)),
                ('time', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumcategory')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
