# Generated by Django 5.0.4 on 2024-06-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_curriculumitem_grade_and_more'),
        ('lessons', '0002_remove_lesson_field'),
        ('users', '0017_advisor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=0)),
                ('test_count', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.advisor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumcategory')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
