# Generated by Django 4.0.6 on 2024-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcategory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='field',
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(default='video', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
