# Generated by Django 4.0.6 on 2024-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contentcategory_type_remove_exam_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=100),
        ),
    ]
