# Generated by Django 4.0.6 on 2024-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('test', 'Test'), ('question', 'Question')], default='test', max_length=100),
        ),
    ]
