# Generated by Django 4.0.6 on 2024-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_exam_grade_exam_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
