# Generated by Django 4.0.6 on 2024-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentcategory_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=30),
        ),
    ]
