# Generated by Django 4.0.6 on 2024-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
