# Generated by Django 4.0.6 on 2024-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contentcategory_is_free_contentcategory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='is_clone',
            field=models.BooleanField(default=False),
        ),
    ]
