# Generated by Django 4.0.6 on 2024-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('closed', 'Closed'), ('in_progress', 'In Progress')], default='in_progress', max_length=100),
        ),
    ]
