# Generated by Django 4.2.7 on 2023-12-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_student_invitation_code_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.field')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
            ],
        ),
    ]
