# Generated by Django 4.0.6 on 2024-03-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='field',
        ),
    ]
