# Generated by Django 5.0.4 on 2024-08-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_advisor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('banner', models.ImageField(upload_to='field/banner/')),
                ('button', models.ImageField(upload_to='field/button/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='field/audio/')),
                ('creator', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.fieldintro')),
            ],
        ),
        migrations.CreateModel(
            name='FieldQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.fieldintro')),
            ],
        ),
    ]
